lib/plots_creator_web/router.ex
defmodule PlotsCreatorWeb.Router do
  use PlotsCreatorWeb, :router

  import PlotsCreatorWeb.UserAuth
  import PlotsCreatorWeb.Plugs.CurrentUser, only: [assign_current_user: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PlotsCreatorWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlotsCreatorWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlotsCreatorWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PlotsCreatorWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PlotsCreatorWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PlotsCreatorWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update

    get "/users/settings/confirm_email/:token",
        UserSettingsController,
        :confirm_email

    live "/your_plots", YourPlotsLive.Index, :index
    live "/your_plots/new", YourPlotsLive.Index, :new
    live "/your_plots/:id/edit", YourPlotsLive.Index, :edit
    live "/your_plots/:id", YourPlotsLive.Show, :show
    live "/your_plots/:id/show/edit", YourPlotsLive.Show, :edit

    live "/shared_with_yous", SharedWithYouLive.Index, :index
    live "/shared_with_yous/new", SharedWithYouLive.Index, :new
    live "/shared_with_yous/:id/edit", SharedWithYouLive.Index, :edit
    live "/shared_with_yous/:id", SharedWithYouLive.Show, :show
    live "/shared_with_yous/:id/show/edit", SharedWithYouLive.Show, :edit
  end

  scope "/", PlotsCreatorWeb do
    pipe_through [:browser]

    post "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/plots_creator_web/controllers/user_registration_controller.ex
defmodule PlotsCreatorWeb.UserRegistrationController do
  use PlotsCreatorWeb, :controller

  alias PlotsCreator.Accounts
  alias PlotsCreator.Accounts.User
  alias PlotsCreatorWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/plots_creator_web/views/user_registration_view.ex
defmodule PlotsCreatorWeb.UserRegistrationView do
  use PlotsCreatorWeb, :view
end

lib/plots_creator_web/templates/user_registration/new.html.heex
<h1 class="text-2xl font-bold mb-6 text-gray-800">Register</h1>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)} class="space-y-6">
  <%= if @changeset.action do %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div>
    <%= label f, :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= email_input f, :email, required: true, class: "mb-5 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, :email %>
  </div>

  <div>
    <%= label f, :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= password_input f, :password, required: true, class: "mb-5 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, :password %>
  </div>

  <div>
    <%= submit "Register", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</.form>

<p class="mt-6 text-center text-gray-600">
  <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "text-blue-500 hover:underline" %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "text-blue-500 hover:underline" %>
</p>